version: "3.7"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq-data/:/var/lib/rabbitmq/
        - ./rabbitmq-logs/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  api-books:
    restart: on-failure
    build: ./Books
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db-books
    networks:
      - books_network
      - rabbitmq_go_net

  
  db-books:
    image: postgres
    
    environment:
       POSTGTES_PASSWORD: 12345
       POSTGRES_DB: library
       POSTGRES_USER: postgres_user
       POSTGRES_HOST_AUTH_METHOD: trust

    networks:
      - books_network

  api-users:
    restart: on-failure
    build: ./Users
    ports:
      - "9898:9898"
    volumes:
      - .:/app  
    networks:
      - rabbitmq_go_net

  api-loans:
    restart: on-failure
    build: ./Loans
    ports:
      - "7778:7778"
    volumes:
      - .:/app
    depends_on:
      - db-loans
    networks:
      - loans_network
      - rabbitmq_go_net
  
  db-loans:
    restart: on-failure
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres_user
      POSTGRES_DB: library-loans
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - loans_network

  api-notifications:
    restart: on-failure
    build: ./Notifications
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
  books_network:
    driver: bridge
  loans_network:
    driver: bridge
  
