name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build 
      run: docker-compose up -d --remove-orphans

  test:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Build 
      run: docker-compose up -d --remove-orphans
    - name: Test 
      run: |
        sleep 120
        python3 Books/test.py
        python3 Users/test.py
        python3 Loans/test.py
